version: "3.7"

networks:
  caching_default:
    external: true
  rabbitmq_default:
    external: true
  traefik_default:
    external: true

services:
  dbus:
    image: twitch-bot-dbus
    build: dbus
    environment:
      - RABBITMQ_URL=amqp://moniquelivebot:moniquelivebot@rabbitmq/twitch?heartbeat=600
      - REDIS_URL=redis:6379
    networks:
      - rabbitmq_default
      - caching_default
    # DBUS stuff
    privileged: true
    user: "1000"
    volumes:
      - /run/user/1000/bus:/run/user/1000/bus

  websocket:
    image: twitch-bot-websocket
    build: websocket
    environment:
      - RABBITMQ_URL=amqp://moniquelivebot:moniquelivebot@rabbitmq/twitch?heartbeat=600
    # ports:
    #   - 9090:9090
    networks:
      - rabbitmq_default
      - traefik_default
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.websocket.rule=Host(`ws.bot.docker.local`)
        - traefik.http.services.bot-websocket.loadbalancer.server.port=9090

  perola:
    image: twitch-bot-perola
    build: perola
    environment:
      - RABBITMQ_URL=amqp://moniquelivebot:moniquelivebot@rabbitmq/twitch?heartbeat=600
    networks:
      - rabbitmq_default

  twitch-stats:
    image: twitch-bot-twitch_stats
    build: twitch_stats
    environment:
      - RABBITMQ_URL=amqp://moniquelivebot:moniquelivebot@rabbitmq/twitch?heartbeat=600
      - REDIS_URL=redis:6379
    networks:
      - rabbitmq_default
      - caching_default

  twitch:
    image: twitch-bot-twitch
    build: twitch
    tty: true
    environment:
      - RABBITMQ_URL=amqp://moniquelivebot:moniquelivebot@rabbitmq/twitch?heartbeat=600
      - REDIS_URL=redis:6379
      - TERM=xterm-256color
    networks:
      - rabbitmq_default
      - caching_default
    volumes:
      - ./twitch/config:/config:ro
